services:
  pasarguardbot:
    build:
      context: .
    container_name: pasarguardbot
    restart: unless-stopped
    user: "0:0"
    env_file:
      - .env
    working_dir: /data
    volumes:
      - ./data:/data
